// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjTfVjt6jTSkknhyFsGPPaucN1ljbtxro',
    appId: '1:837436786756:web:6288b6f41b90c715845411',
    messagingSenderId: '837436786756',
    projectId: 'job-push-notify',
    authDomain: 'job-push-notify.firebaseapp.com',
    storageBucket: 'job-push-notify.appspot.com',
    measurementId: 'G-RJLSJVPP3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPg4VAdvhtW4d8qq5Zo5W8SJFxYoSlaCw',
    appId: '1:837436786756:android:d254046aec7e0bbd845411',
    messagingSenderId: '837436786756',
    projectId: 'job-push-notify',
    storageBucket: 'job-push-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEA9Pi1WYRNhgi24hkEU9h_bcts467zT4',
    appId: '1:837436786756:ios:2a7b8ebb986e1e77845411',
    messagingSenderId: '837436786756',
    projectId: 'job-push-notify',
    storageBucket: 'job-push-notify.appspot.com',
    iosBundleId: 'vn.iotstar.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEA9Pi1WYRNhgi24hkEU9h_bcts467zT4',
    appId: '1:837436786756:ios:2a7b8ebb986e1e77845411',
    messagingSenderId: '837436786756',
    projectId: 'job-push-notify',
    storageBucket: 'job-push-notify.appspot.com',
    iosBundleId: 'vn.iotstar.foodDelivery',
  );
}
